version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas:8080
functions:
  moon-phase:
    lang: golang-middleware
    handler: ./moon-phase
    image: sriveros95/moon-phase:latest
  moon-farmer:
    lang: golang-middleware
    handler: ./moon-farmer
    image: sriveros95/moon-farmer:latest
  agro-ui:
    lang: dockerfile
    handler: ./agro-ui
    image: agro-ui:latest
